name: Docker Image CI(Dockerfile.dev)

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      CURRENT_DATE: $(date +%s)

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image using Dockerfile.dev
      run: docker build . -f Dockerfile.dev -t daniel/docker-react-pr-test:$(date +%s)
    - name: Run npm tests
      run: docker run daniel/docker-react-pr-test:$(date +%s) npm run test -- --coverage
