name: Docker Image CI(Dockerfile.dev)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CURRENT_DATE: $(date +%s)

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image using Dockerfile.dev
        run: docker build . -f Dockerfile.dev -t daniel/docker-react-pr-test:${{ CURRENT_DATE }}
      - name: Run npm tests
        run: docker run daniel/docker-react-pr-test:${{ CURRENT_DATE }} npm run test -- --coverage
