name: Docker Image CI(Dockerfile.dev)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image using Dockerfile.dev
        run: docker build . -f Dockerfile.dev -t daniel/docker-react-pr-test:$GITHUB_RUN_ID
      - name: npm CI
        run: docker run daniel/docker-react-pr-test:$GITHUB_RUN_ID npm ci
      - name: npm build
        run: docker run daniel/docker-react-pr-test:$GITHUB_RUN_ID npm run build --if-present
        env:
          CI: true
      - name: npm test
        run: docker run daniel/docker-react-pr-test:$GITHUB_RUN_ID npm run test --CI=true --watchAll=false
        env:
          CI: true