name: Docker Image CI(Dockerfile.dev)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image using Dockerfile.dev
        run: |
         docker build . -f Dockerfile.dev -t daniel/docker-react-pr-test:$GITHUB_RUN_ID
         docker run daniel/docker-react-pr-test:$GITHUB_RUN_ID npm ci
         docker run daniel/docker-react-pr-test:$GITHUB_RUN_ID npm run build --if-present
         docker run daniel/docker-react-pr-test:$GITHUB_RUN_ID npm run test
        env:
          CI: true