name: Docker Image CI(Dockerfile.dev)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build the Docker image using Dockerfile.dev
        run: docker build . -f Dockerfile.dev -t daniel/docker-react-pr-test:$GITHUB_RUN_ID
      - name: Run npm tests
        run: docker run daniel/docker-react-pr-test:$GITHUB_RUN_ID CI=true npm run test -- --coverage
        env:
          CI: true